TEMPLATE = app
DESTDIR = dist/Debug/None-Windows
TARGET = RunSeppRu
VERSION = 1.0.0
CONFIG -= debug_and_release app_bundle lib_bundle
CONFIG += debug 
QT = core gui
SOURCES += main.cpp
HEADERS +=
FORMS +=
RESOURCES +=
TRANSLATIONS +=
OBJECTS_DIR = build/Debug/None-Windows
MOC_DIR = 
RCC_DIR = 
UI_DIR = 
QMAKE_CC = 
QMAKE_CXX = 
DEFINES += 
INCLUDEPATH += 
LIBS += 
